- bin/init.js
- composer.json
Changes composer package name to `rtcamp/elementary` from `rtcamp/elementary-theme`. Makes necessary changes in the `init` script to handle the search-replace in `composer.json` file separately.
- The aim was to have the package name as `rtcamp/elementary` instead of `rtcamp/elementary-theme`. The package name was `rtcamp/elementary-theme` in the first place because keeping it `rtcamp/elementary` causes the search-replace to conflict between the theme name and function prefix for example.
- The PR also includes some other minor code cleanup and fixes/improvements.
> Change theme package name 

- composer.json
Set `minimum-stability`  to `dev`
Fixes #
> Add minimum-stability for composer

- README.md
- package.json
NPM scripts `dev` and `start` have associated executable as `wp-scripts start`, so removed `npm:dev` script.
- Remove `npm:dev` script
- Update `Watch changes` script in README.md file.
Fixes #
> Fix duplicate npm script

- README.md
- composer.json
- package-lock.json
Update readme with the `How to get started` section.
- Update composer configuration to trigger `npm i` after `composer install` finishes.
Fixes #
> Add `composer create-command` in readme

- styles/light.json
- templates/blank.html
- templates/no-title.html
- theme.json
Adds Global Styles Variations and custom template
- Adds a Global Style Variation (Note: You will need the Gutenberg plugin activated for this to work, or WP 6.0)
- Adds a custom template for demonstration named `No title`
- Demonstrates custom typography configuration in `theme.json` file.
Fixes #7
> Add Global Styles Variations and custom template

- bin/init.js
- package.json
Fixes PHP error after theme initialization's search-replace and adds theme cleanup post search-replace.
- Autoload files need to be recreated after the `search-replace` during the theme initialization.
- Adds 
Fixes #37
> Autoload fix and cleanup on theme initialization

- .github/dependabot.yml
Adds `dependabot.yml` file with necessary configuration.
Fixes #
> Add `dependabot.yml` file

- .github/workflows/lint-js-css.yml
- .npmpackagejsonlintrc.json
- package.json
Adds JS & CSS lint checks on PRs
Fixes #
> Add JS & CSS lint actions on PRs

- .github/workflows/test-measure.yml
This PR is a follow-up to https://github.com/rtCamp/theme-elementary/pull/69#discussion_r883652944
After taking references from many other repos I found that this is not a common repo so removing this feature.
Fixes #
> Remove build label on PR

- .github/dependabot.yml
This PR aims to update dependabot configurations.
- Update interval to daily because in weekly there is a number of PRs which are difficult to review and merge because with each merge dependabot rebases the PR(that also causes GHA runs many times) that is time taking.
- Remove `versioning-strategy` as by default npm and composer is `increase`
- Add label based on package ecosystem. 
Fixes #
> Update dependabot schedule and labels configurations

- .github/bin/gutenberg-packages-update-pr-body.js
- .github/dependabot.yml
- .github/workflows/auto-merge.yml
- .github/workflows/gutenberg-packages-update.yml
This PR aims to add these two workflows:
1. `Gutenberg packages update` - Will update `@wordpress/* NPM packages based on Gutenberg releases`
2. `Auto Merge` - Auto merge dependabot and `Gutenberg packages update` PRs once the `Test and Measure` workflow passed.
These workflows will require two new secrets to be added:
- `PR_REVIEWER` user name which needs to add as PR reviewer on `Gutenberg packages update` PRs. The idea behind this is to send notifications to a maintainer to keep track of such PRs.
Fixes #
> Add `Auto Merge` and `Gutenberg packages update` workflows

- .github/workflows/auto-merge.yml
> Fix steps conditions

- .github/workflows/auto-merge.yml
- .github/workflows/gutenberg-packages-update.yml
> Fix steps conditions and add rtBot user

- .github/workflows/gutenberg-packages-update.yml
After failing workflow - https://github.com/rtCamp/theme-elementary/runs/7122556657?check_suite_focus=true I found the script path was not correct. So fix the file path.
Fixes #
> Fix path of pr-body generator file

- .github/workflows/gutenberg-packages-update.yml
> Fix label names

- README.md
- bin/git-init.sh
- package.json
- Add script to initialize git, before `huksy install` if not present
- Update project setup command(using composer)
> Add script to init git before husky init

- README.md
Updates the project description in the readme file with better wording.
> Update project description in the readme file

- assets/src/css/core-navigation.scss
- assets/src/js/core-navigation.js
- inc/classes/class-assets.php
- inc/classes/class-elementary-theme.php
- inc/classes/patterns/class-block-patterns.php
- inc/classes/patterns/content/class-footer.php
- inc/classes/patterns/content/class-hidden-404.php
- index.php
- webpack.config.js
Adds scripts and styles injection samples along with a couple of other fixes and adjustments.
- Adds sample scripts and styles configuration along with block-specific injection sample.
- Fixes a PHPCS error in the `class-footer.php` file.
- Removes the `index.php` file from the theme root as it's not required anymore by WordPress.
> Add scripts and styles injection samples

- README.md
Fix spelling mistake at `README.md` file.
Fixes #398
> fix - typo at README.md

- README.md
- README.md updated.
```diff
- composer install && npm install
+ composer install
```
- composer install was running npm i command so npm install was getting executed twice with this command `composer install && npm install` modified it to only `composer install`
- Fixes #412
> GH-412: Dependency installation runs twice if user follows method 2 as mentioned in README file.
